config:
  credentials:
  - id: https://github.com/PalomoIFCA/private3
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private3:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private3
      repo: https://github.com/PalomoIFCA/private3
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private3 git:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_wondrous_goose.sh
        container: qc.acc_thistle_grateful_tortoise
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private3 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flint_articulate_finch.sh
        container: qc.doc_pine_visionary_goat
      github.com/PalomoIFCA/private3 git:
        commands:
        - /usr/bin/env sh .sqa/script.poppy_productive_beaver.sh
        container: qc.doc_persimmon_protective_donkey
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private3 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.saffron_jubilant_emu.sh
        container: qc.lic_tide_humble_rhinoceros
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private3 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.raven_foolish_reindeer.sh
        container: qc.sec_onyx_gentle_rhinoceros
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private3 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.copper_relaxed_tarantula.sh
        container: qc.sty_mustard_dreamy_viper
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private3 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_audacious_platypus.sh
        container: qc.uni_ecru_cautious_crow
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private3 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.onyx_rugged_coyote.sh
        container: qc.ver_copper_polite_ibex
timeout: 5400
