config:
  credentials:
  - id: https://github.com/PalomoIFCA/private3
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private3:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private3
      repo: https://github.com/PalomoIFCA/private3
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private3 git:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_serene_catfish.sh
        container: qc.acc_cerise_meticulous_squid
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private3 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pink_sympathetic_jaguar.sh
        container: qc.doc_cerise_methodical_kangaroo
      github.com/PalomoIFCA/private3 git:
        commands:
        - /usr/bin/env sh .sqa/script.grege_vigilant_narwhal.sh
        container: qc.doc_flint_bold_crocodile
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private3 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.currant_diligent_anaconda.sh
        container: qc.lic_pine_warm_squirrel
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private3 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.peach_curious_manta.sh
        container: qc.sec_green_joyful_bear
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private3 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.marina_passionate_raven.sh
        container: qc.sty_red_fierce_salamander
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private3 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.aqua_devoted_walrus.sh
        container: qc.uni_eggplant_grateful_boar
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private3 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bronze_content_wombat.sh
        container: qc.ver_khaki_assured_buffalo
timeout: 5400
