config:
  credentials:
  - id: https://github.com/PalomoIFCA/private3
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private3:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private3
      repo: https://github.com/PalomoIFCA/private3
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private3 git:
        commands:
        - /usr/bin/env sh .sqa/script.sienna_skeptical_dormouse.sh
        container: qc.acc_dawn_spontaneous_hamster
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private3 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.isabelline_perky_rattlesnake.sh
        container: qc.doc_ginger_frugal_stingray
      github.com/PalomoIFCA/private3 git:
        commands:
        - /usr/bin/env sh .sqa/script.pansy_realistic_grasshopper.sh
        container: qc.doc_claret_stubborn_dugong
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private3 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.amethyst_unique_bat.sh
        container: qc.lic_aqua_lucky_meerkat
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private3 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.green_decisive_chimpanzee.sh
        container: qc.sec_navy_silly_osprey
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private3 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gold_foolish_dingo.sh
        container: qc.sty_amethyst_mature_thrush
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private3 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.apricot_humble_spider.sh
        container: qc.uni_jade_respectful_cassowary
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private3 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_grumpy_jellyfish.sh
        container: qc.ver_pumpkin_inspired_toad
timeout: 5400
